export const TYPE_COLOR_MAPPING: Record<string, string> = {
    'bug': 'bg-lime-300',
    'bug-text': 'text-stone-900',
    'grass': 'bg-lime-800',
    'grass-text': 'text-white',
    'dark': 'bg-zinc-800',
    'dark-text': 'text-white',
    'ground':'bg-yellow-200',
    'ground-text': 'text-yellow-900',
    'dragon':'bg-purple-600',
    'dragon-text':'text-white',
    'ice':'bg-cyan-200',
    'ice-text':'text-cyan-800',
    'electric':'bg-yellow-300',
    'electric-text':'text-black',
    'normal':'bg-orange-200',
    'normal-text':'text-orange-900',
    'fairy':'bg-fuchsia-300',
    'fairy-text':'text-black',
    'poison':'bg-purple-600',
    'poison-text':'text-white',
    'fighting':'bg-orange-900',
    'fighting-text':'text-white',
    'psychic':'bg-purple-600',
    'psychic-text':'text-white',
    'fire':'bg-red-500',
    'fire-text':'text-white',
    'rock':'bg-stone-600',
    'rock-text':'text-white',
    'flying':'bg-indigo-300',
    'flying-text':'text-black',
    'steel':'bg-stone-700',
    'steel-text':'#text-white',
    'ghost':'bg-purple-600',
    'ghost-text':'text-white',
    'water':'bg-blue-600',
    'water-text':'text-white',
};
